### PR TITLE
Add Binance, Avalanche, Fantom chains support

### PR DESCRIPTION
**Pull request by udhriaznov**
## Background

We want to support as many chains as possible and Moralis API gives us the ability to support not just Ethereum and Polygon networks, but several others as well. 

## Related Story / Issue

https://linear.app/unstoppable-domains/issue/ECUX-94/nft-api-add-support-for-all-moralis-chains

## Changes

- Added support in our NFT API for Binance, Avalanche and Fantom chain from the Moralis API

### CODE REVIEW

**Review by iurevych — APPROVED** [review]
LGTM but let's also get @sudoryan review. I'm also wondering where do we get JSON RPC URLs from.

**Comment by sudoryan** [comment]
LGTM! 

The JSON RPC URLS env config is stored under https://github.com/unstoppabledomains/resolution-service/settings/secrets/actions

**Comment by udhriaznov** [comment]
@sudoryan They are EVM compatible. And, as I see in their Blockchain Explorers, they work with erc721.
Binance Smart Chain - https://bscscan.com/
Avalanche - https://snowtrace.io/
Fantom - https://ftmscan.com/

Binance Smart Chain also supports erc1155, but I'm not sure about other two chains.

**Review by sudoryan — APPROVED** [review]
LGTM

**Pull request merged**
